### PR TITLE
Email

### LINKED ISSUE #74: Configure email
It would be good to set up the `@samhstn.com` email addresses.

We don't want to be paying $4 per month with using [WorkMail](https://aws.amazon.com/workmail/pricing/).

Instead, it would be best to opt for a cheaper setup using just lambda and s3.

- [ ] Configure lambda function which logs email in cloudwatch
- [ ] Configure lambda function which writes email to s3.
- [ ] Configure lambda function to also send an email notification when an email arrives.

For now all emails can be read using the command line, or viewing them through the s3 console. We can worry about a more maintainable way to manage emails later.

### PR DESCRIPTION
**Pull request by samhstn**
Fixes #74

### CODE REVIEW

**Review by nelsonic — APPROVED** [review]
@samhstn looks good. 👍
Only thing I would change is the "noreply".
But not a blocker.
🚀

**Comment by samhstn** [comment]
Thanks @nelsonic 🚀 what would you use instead of `noreply`?

**Comment by samhstn** [comment]
No probs, found the explanation here: https://github.com/dwyl/hq/issues/468

**Comment by nelsonic** [comment]
I find "noreply" to be a UX antipattern https://github.com/dwyl/hq/issues/468#issuecomment-459090844
If you're only using the email for _receiving_ and this is just a default I would set it to "hello".
But if you're _sending_ outbound, there's definitely a more friendly option.

**Pull request merged**
